### PR TITLE
Windows Fixes (DONE)

### PR DESCRIPTION
**Pull request by cypherix93**
This still needs a bit of work. But I managed to solve most of the compilation issues on Windows. The remaining problems are these:

upload 71

Maybe someone else can help.

### CODE REVIEW

**Comment by st0ffern** [comment]
@cypherix93 Is this complete now or do you need more fixes?

**Comment by cypherix93** [comment]
@stoffern I think I just wrapped it up. It works as far as Windows and Linux are concerned!

**Comment by st0ffern** [comment]
nice work @cypherix93 :+1: 
just tested now and it compiles without problems on windows
(env: node6, msvs2015)

Have you tested it so it still compiles on linux? :smile:

**Comment by cypherix93** [comment]
@stoffern I just did on my Ubuntu box. It works great! :smile:

**Comment by st0ffern** [comment]
@cypherix93 awsome, great work!
Then i can continue on my API :+1:

**Comment by st0ffern** [comment]
cc @billyriantono

**Comment by cypherix93** [comment]
@stoffern I am chatting with him right now. He wants to make sure it works on his Mac too.

**Comment by billyriantono** [comment]
@cypherix93 please make a PR from branch alternative, and please help test on windows. that version have been successfully compiled in my mac .. thanks

**Comment by st0ffern** [comment]
@billyriantono i have used it today on my [pokemon-go-api](https://github.com/stoffern/pokemon-go-api) and all the functions works fine.
compiled on windows with both node v6 and v4

**Comment by billyriantono** [comment]
@stoffern yaps it's PR can build on Windows but can't compiled in Mac, so i make adjustment also in @cypherix93  repo 😄

**Comment by cypherix93** [comment]
Please check #10 for a better PR. That version works on Mac as well. Closing this.

**Pull request closed without merging**
